[package]
name = "uwu-sources"
version = "0.1.0"
edition = "2021"

[dependencies]
uwu-schema.workspace = true
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
notify.workspace = true
log.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_EventLog",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
] }
