[package]
name = "uwu-core-workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
tokio.workspace = true
uwu-core-engine = { workspace = true }
uwu-core-schema = { workspace = true }
uwu-driver-sources = { workspace = true }
uwu-driver-transport = { workspace = true }

