[package]
name = "uwu-tui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uwu-log"
path = "src/main.rs"

[dependencies]
uwu-schema.workspace = true
uwu-sources.workspace = true
uwu-engine.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
anyhow.workspace = true
log.workspace = true
uuid.workspace = true
