[package]
name = "uwu-driver-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
uwu-core-protocol.workspace = true
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
log.workspace = true
uwu-core-util.workspace = true
serde.workspace = true

[target.'cfg(windows)'.dependencies]
windows-registry.workspace = true
