use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=../../packaging/assets/icon.ico");

    #[cfg(windows)]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("../../packaging/assets/icon.ico");
        res.set("FileDescription", "Uwu Log Viewer");
        res.set("ProductName", "Uwu Log");
        res.set("OriginalFilename", "uwu-gui.exe");
        if let Err(e) = res.compile() {
            eprintln!("Warning: Failed to compile Windows resource: {}", e);
        }
    }

    generate_icon_vector_data();
}

fn snake_to_camel(s: &str) -> String {
    let mut camel = String::new();
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            camel.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            camel.push(c);
        }
    }
    camel
}

fn sample_cubic(
    p0: (f32, f32),
    p1: (f32, f32),
    p2: (f32, f32),
    p3: (f32, f32),
    steps: usize,
) -> Vec<(f32, f32)> {
    let mut pts = Vec::with_capacity(steps);
    for i in 1..=steps {
        let t = i as f32 / steps as f32;
        let u = 1.0 - t;
        let x =
            u * u * u * p0.0 + 3.0 * u * u * t * p1.0 + 3.0 * u * t * t * p2.0 + t * t * t * p3.0;
        let y =
            u * u * u * p0.1 + 3.0 * u * u * t * p1.1 + 3.0 * u * t * t * p2.1 + t * t * t * p3.1;
        let x = (x * 1000.0).round() / 1000.0;
        let y = (y * 1000.0).round() / 1000.0;
        pts.push((x, y));
    }
    pts
}

fn sample_quadratic(
    p0: (f32, f32),
    p1: (f32, f32),
    p2: (f32, f32),
    steps: usize,
) -> Vec<(f32, f32)> {
    let mut pts = Vec::with_capacity(steps);
    for i in 1..=steps {
        let t = i as f32 / steps as f32;
        let u = 1.0 - t;
        let x = u * u * p0.0 + 2.0 * u * t * p1.0 + t * t * p2.0;
        let y = u * u * p0.1 + 2.0 * u * t * p1.1 + t * t * p2.1;
        let x = (x * 1000.0).round() / 1000.0;
        let y = (y * 1000.0).round() / 1000.0;
        pts.push((x, y));
    }
    pts
}

fn get_inherited_attribute<'a>(node: &'a roxmltree::Node<'a, 'a>, attr: &str) -> Option<&'a str> {
    let mut curr = Some(*node);
    while let Some(n) = curr {
        if let Some(val) = n.attribute(attr) {
            return Some(val);
        }
        if n.tag_name().name() == "svg" {
            break;
        }
        curr = n.parent();
    }
    None
}

fn is_ignored_element(node: &roxmltree::Node) -> bool {
    let mut curr = Some(*node);
    while let Some(n) = curr {
        match n.tag_name().name() {
            "defs" | "mask" | "clipPath" => return true,
            _ => curr = n.parent(),
        }
    }
    false
}

#[derive(Debug)]
enum CodegenShape {
    StrokedPath {
        point_array_name: String,
        stroke_width: f32,
    },
    StrokedClosedPath {
        point_array_name: String,
        stroke_width: f32,
    },
    FilledPolygon {
        point_array_name: String,
        opacity: f32,
    },
    StrokedCircle {
        cx: f32,
        cy: f32,
        r: f32,
        stroke_width: f32,
    },
    FilledCircle {
        cx: f32,
        cy: f32,
        r: f32,
        opacity: f32,
    },
    StrokedRect {
        min_x: f32,
        min_y: f32,
        max_x: f32,
        max_y: f32,
        corner_r: f32,
        stroke_width: f32,
    },
    FilledRect {
        min_x: f32,
        min_y: f32,
        max_x: f32,
        max_y: f32,
        corner_r: f32,
        opacity: f32,
    },
    LineSegment {
        x1: f32,
        y1: f32,
        x2: f32,
        y2: f32,
        stroke_width: f32,
    },
}

fn generate_icon_vector_data() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let icons_dir = manifest_dir.join("assets").join("icons");

    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let mut entries: Vec<_> = fs::read_dir(&icons_dir)
        .unwrap_or_else(|e| panic!("Failed to read icons dir {:?}: {}", icons_dir, e))
        .filter_map(Result::ok)
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "svg"))
        .collect();

    entries.sort_by_key(|e| e.file_name());

    let mut out = String::new();
    out.push_str("// Autogenerated compile-time SVG vector data from assets/icons/*.svg\n");
    out.push_str("// DO NOT EDIT DIRECTLY. Run `cargo build` to regenerate.\n\n");

    let mut match_arms = Vec::new();

    for entry in &entries {
        let path = entry.path();
        let stem = path.file_stem().unwrap().to_str().unwrap();
        let variant_name = snake_to_camel(stem);
        let upper_stem = stem.to_ascii_uppercase();

        let svg_text = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Failed to read {:?}: {}", path, e));

        let doc = roxmltree::Document::parse(&svg_text)
            .unwrap_or_else(|e| panic!("Failed to parse XML in {:?}: {}", path, e));

        let mut point_arrays: Vec<(String, Vec<(f32, f32)>)> = Vec::new();
        let mut shapes: Vec<CodegenShape> = Vec::new();
        let mut array_counter = 0;

        for node in doc.descendants() {
            if is_ignored_element(&node) {
                continue;
            }

            let stroke_attr = get_inherited_attribute(&node, "stroke");
            let fill_attr = get_inherited_attribute(&node, "fill");
            let stroke_width_attr = get_inherited_attribute(&node, "stroke-width");
            let opacity_attr = get_inherited_attribute(&node, "opacity");

            let stroke_width: f32 = stroke_width_attr
                .and_then(|s| s.parse().ok())
                .unwrap_or(1.2);

            let opacity: f32 = opacity_attr.and_then(|s| s.parse().ok()).unwrap_or(1.0);

            let has_stroke = stroke_attr.is_some_and(|s| s != "none" && !s.is_empty());
            let has_fill =
                fill_attr.is_some_and(|f| f == "currentColor" || (f != "none" && !f.is_empty()));

            match node.tag_name().name() {
                "circle" => {
                    let cx: f32 = node
                        .attribute("cx")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let cy: f32 = node
                        .attribute("cy")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let r: f32 = node
                        .attribute("r")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);

                    if has_fill {
                        shapes.push(CodegenShape::FilledCircle { cx, cy, r, opacity });
                    }
                    if has_stroke || !has_fill {
                        shapes.push(CodegenShape::StrokedCircle {
                            cx,
                            cy,
                            r,
                            stroke_width,
                        });
                    }
                }
                "rect" => {
                    let x: f32 = node
                        .attribute("x")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let y: f32 = node
                        .attribute("y")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let width: f32 = node
                        .attribute("width")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let height: f32 = node
                        .attribute("height")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let rx: f32 = node
                        .attribute("rx")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);

                    if has_fill {
                        shapes.push(CodegenShape::FilledRect {
                            min_x: x,
                            min_y: y,
                            max_x: x + width,
                            max_y: y + height,
                            corner_r: rx,
                            opacity,
                        });
                    }
                    if has_stroke || !has_fill {
                        shapes.push(CodegenShape::StrokedRect {
                            min_x: x,
                            min_y: y,
                            max_x: x + width,
                            max_y: y + height,
                            corner_r: rx,
                            stroke_width,
                        });
                    }
                }
                "line" => {
                    let x1: f32 = node
                        .attribute("x1")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let y1: f32 = node
                        .attribute("y1")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let x2: f32 = node
                        .attribute("x2")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);
                    let y2: f32 = node
                        .attribute("y2")
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0.0);

                    shapes.push(CodegenShape::LineSegment {
                        x1,
                        y1,
                        x2,
                        y2,
                        stroke_width,
                    });
                }
                "path" => {
                    let d = match node.attribute("d") {
                        Some(d) => d,
                        None => continue,
                    };

                    let mut subpaths: Vec<(Vec<(f32, f32)>, bool)> = Vec::new();
                    let mut current_subpath: Vec<(f32, f32)> = Vec::new();
                    let mut current_pos = (0.0f32, 0.0f32);
                    let mut is_closed = false;

                    for segment in svgtypes::SimplifyingPathParser::from(d) {
                        let seg = match segment {
                            Ok(s) => s,
                            Err(e) => panic!("Error parsing path d in {:?}: {}", path, e),
                        };

                        match seg {
                            svgtypes::SimplePathSegment::MoveTo { x, y } => {
                                if !current_subpath.is_empty() {
                                    subpaths.push((current_subpath, is_closed));
                                    current_subpath = Vec::new();
                                    is_closed = false;
                                }
                                let p = (
                                    (x as f32 * 1000.0).round() / 1000.0,
                                    (y as f32 * 1000.0).round() / 1000.0,
                                );
                                current_subpath.push(p);
                                current_pos = p;
                            }
                            svgtypes::SimplePathSegment::LineTo { x, y } => {
                                let p = (
                                    (x as f32 * 1000.0).round() / 1000.0,
                                    (y as f32 * 1000.0).round() / 1000.0,
                                );
                                if current_subpath.is_empty() {
                                    current_subpath.push(current_pos);
                                }
                                current_subpath.push(p);
                                current_pos = p;
                            }
                            svgtypes::SimplePathSegment::CurveTo {
                                x1,
                                y1,
                                x2,
                                y2,
                                x,
                                y,
                            } => {
                                if current_subpath.is_empty() {
                                    current_subpath.push(current_pos);
                                }
                                let p1 = (x1 as f32, y1 as f32);
                                let p2 = (x2 as f32, y2 as f32);
                                let p3 = (x as f32, y as f32);
                                let sampled = sample_cubic(current_pos, p1, p2, p3, 4);
                                for pt in sampled {
                                    current_subpath.push(pt);
                                }
                                current_pos = (
                                    (x as f32 * 1000.0).round() / 1000.0,
                                    (y as f32 * 1000.0).round() / 1000.0,
                                );
                            }
                            svgtypes::SimplePathSegment::Quadratic { x1, y1, x, y } => {
                                if current_subpath.is_empty() {
                                    current_subpath.push(current_pos);
                                }
                                let p1 = (x1 as f32, y1 as f32);
                                let p2 = (x as f32, y as f32);
                                let sampled = sample_quadratic(current_pos, p1, p2, 4);
                                for pt in sampled {
                                    current_subpath.push(pt);
                                }
                                current_pos = (
                                    (x as f32 * 1000.0).round() / 1000.0,
                                    (y as f32 * 1000.0).round() / 1000.0,
                                );
                            }
                            svgtypes::SimplePathSegment::ClosePath => {
                                is_closed = true;
                                if !current_subpath.is_empty() {
                                    subpaths.push((current_subpath, is_closed));
                                    current_subpath = Vec::new();
                                    is_closed = false;
                                }
                            }
                        }
                    }

                    if !current_subpath.is_empty() {
                        subpaths.push((current_subpath, is_closed));
                    }

                    for (mut pts, closed) in subpaths {
                        // De-duplicate consecutive points
                        pts.dedup_by(|a, b| (a.0 - b.0).abs() < 0.001 && (a.1 - b.1).abs() < 0.001);

                        // If closed and first == last, remove duplicate last point
                        if closed && pts.len() > 2 {
                            let first = pts[0];
                            let last = pts[pts.len() - 1];
                            if (first.0 - last.0).abs() < 0.001 && (first.1 - last.1).abs() < 0.001
                            {
                                pts.pop();
                            }
                        }

                        if pts.len() < 2 {
                            continue;
                        }

                        let array_name = format!("{}_P{}", upper_stem, array_counter);
                        array_counter += 1;

                        let mut array_registered = false;

                        if has_fill {
                            point_arrays.push((array_name.clone(), pts.clone()));
                            array_registered = true;
                            shapes.push(CodegenShape::FilledPolygon {
                                point_array_name: array_name.clone(),
                                opacity,
                            });
                        }

                        if has_stroke || !has_fill {
                            if pts.len() == 2 {
                                shapes.push(CodegenShape::LineSegment {
                                    x1: pts[0].0,
                                    y1: pts[0].1,
                                    x2: pts[1].0,
                                    y2: pts[1].1,
                                    stroke_width,
                                });
                            } else {
                                if !array_registered {
                                    point_arrays.push((array_name.clone(), pts));
                                }
                                if closed {
                                    shapes.push(CodegenShape::StrokedClosedPath {
                                        point_array_name: array_name,
                                        stroke_width,
                                    });
                                } else {
                                    shapes.push(CodegenShape::StrokedPath {
                                        point_array_name: array_name,
                                        stroke_width,
                                    });
                                }
                            }
                        }
                    }
                }
                _ => {}
            }
        }

        // Emit static point arrays for this icon
        for (arr_name, pts) in point_arrays {
            out.push_str(&format!("static {}: &[(f32, f32)] = &[\n", arr_name));
            for pt in pts {
                out.push_str(&format!("    ({:.4}, {:.4}),\n", pt.0, pt.1));
            }
            out.push_str("];\n\n");
        }

        // Emit static shape array for this icon
        let shape_array_name = format!("{}_SHAPES", upper_stem);
        out.push_str(&format!(
            "static {}: &[VectorShape] = &[\n",
            shape_array_name
        ));
        for shape in shapes {
            match shape {
                CodegenShape::StrokedPath {
                    point_array_name,
                    stroke_width,
                } => {
                    out.push_str(&format!(
                        "    VectorShape::StrokedPath {{ points: {}, stroke_width: {:.2} }},\n",
                        point_array_name, stroke_width
                    ));
                }
                CodegenShape::StrokedClosedPath {
                    point_array_name,
                    stroke_width,
                } => {
                    out.push_str(&format!(
                        "    VectorShape::StrokedClosedPath {{ points: {}, stroke_width: {:.2} }},\n",
                        point_array_name, stroke_width
                    ));
                }
                CodegenShape::FilledPolygon {
                    point_array_name,
                    opacity,
                } => {
                    out.push_str(&format!(
                        "    VectorShape::FilledPolygon {{ points: {}, opacity: {:.2} }},\n",
                        point_array_name, opacity
                    ));
                }
                CodegenShape::StrokedCircle {
                    cx,
                    cy,
                    r,
                    stroke_width,
                } => {
                    out.push_str(&format!(
                        "    VectorShape::StrokedCircle {{ cx: {:.4}, cy: {:.4}, r: {:.4}, stroke_width: {:.2} }},\n",
                        cx, cy, r, stroke_width
                    ));
                }
                CodegenShape::FilledCircle { cx, cy, r, opacity } => {
                    out.push_str(&format!(
                        "    VectorShape::FilledCircle {{ cx: {:.4}, cy: {:.4}, r: {:.4}, opacity: {:.2} }},\n",
                        cx, cy, r, opacity
                    ));
                }
                CodegenShape::StrokedRect {
                    min_x,
                    min_y,
                    max_x,
                    max_y,
                    corner_r,
                    stroke_width,
                } => {
                    out.push_str(&format!(
                        "    VectorShape::StrokedRect {{ min_x: {:.4}, min_y: {:.4}, max_x: {:.4}, max_y: {:.4}, corner_r: {:.4}, stroke_width: {:.2} }},\n",
                        min_x, min_y, max_x, max_y, corner_r, stroke_width
                    ));
                }
                CodegenShape::FilledRect {
                    min_x,
                    min_y,
                    max_x,
                    max_y,
                    corner_r,
                    opacity,
                } => {
                    out.push_str(&format!(
                        "    VectorShape::FilledRect {{ min_x: {:.4}, min_y: {:.4}, max_x: {:.4}, max_y: {:.4}, corner_r: {:.4}, opacity: {:.2} }},\n",
                        min_x, min_y, max_x, max_y, corner_r, opacity
                    ));
                }
                CodegenShape::LineSegment {
                    x1,
                    y1,
                    x2,
                    y2,
                    stroke_width,
                } => {
                    out.push_str(&format!(
                        "    VectorShape::LineSegment {{ x1: {:.4}, y1: {:.4}, x2: {:.4}, y2: {:.4}, stroke_width: {:.2} }},\n",
                        x1, y1, x2, y2, stroke_width
                    ));
                }
            }
        }
        out.push_str("];\n\n");

        match_arms.push(format!(
            "        IconName::{} => {},\n",
            variant_name, shape_array_name
        ));
    }

    // Emit lookup function
    out.push_str("/// Returns the static vector shape primitives for the given icon.\n");
    out.push_str("#[inline]\n");
    out.push_str("pub const fn get_icon_shapes(icon: IconName) -> &'static [VectorShape] {\n");
    out.push_str("    match icon {\n");
    for arm in match_arms {
        out.push_str(&arm);
    }
    out.push_str("    }\n");
    out.push_str("}\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set by Cargo");
    let dest_path = Path::new(&out_dir).join("icon_vector_data.rs");
    fs::write(&dest_path, out).unwrap_or_else(|e| panic!("Failed to write {:?}: {}", dest_path, e));
}
