[package]
name = "uwu-ui-tui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uwu-tui"
path = "src/main.rs"

[dependencies]
uwu-core-engine.workspace = true
uwu-driver-sources.workspace = true
uwu-core-schema.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
anyhow.workspace = true
log.workspace = true
uuid.workspace = true
